### ISSUE TITLE
Problem in the installation..

### ISSUE THREAD

**Issue by ghost** [dolphyn/dolphyn#1]
Hi ! I've follow the instruction for install Dolphyn but don't work :( 
After run make install for install Dolphyn I've:

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/var/node-www/dolphyn/install/../conf/conf.json'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.writeFileSync (fs.js:971:15)
    at Object.mergeConf (/var/node-www/dolphyn/install/ConfigurationManager.js:39:6)
    at /var/node-www/dolphyn/install/configure-database.js:49:13
    at /var/node-www/dolphyn/install/ConfigurationHandler.js:40:11
    at /var/node-www/dolphyn/install/ConfigurationHandler.js:87:7
    at /var/node-www/dolphyn/install/IOHelper.js:57:11
    at ReadStream.listen (/var/node-www/dolphyn/install/IOHelper.js:103:5)
    at ReadStream.EventEmitter.emit (events.js:95:17)
    at ReadStream.<anonymous> (_stream_readable.js:746:14)
make: **\* [configure] Error 8

An idea ?

**Comment by tvass** [comment]
@nherment Is your project still alive ? I would be highly interested to contribute. Thanks.

**Comment by nherment** [comment]
uhh, that issue was opened 2 months ago ? Github really need to fix notifications...

@kernel23 I'm not actively working on it anymore. I can help get you started on taking it over if you want.

**Comment by tvass** [comment]
@ghost : you need to configure mongodb like this ...

> use dolphyn-mail
> switched to db dolphyn-mail
> db.addUser({user:"root", pwd:"blabla",roles:[ "userAdminAnyDatabase", "readWrite" ] } )

... then node install/configure.js (you might need to mkdir or touch some files like conf/conf.json).

@nherment : I'll try to "play"with it first then see if i can contribute ( i am not nodejs advanced coder). Thanks for your answer.
